#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 정사원 재택근무 IT 엔지니어의 블로그

# Short bio or description (displayed in the header)
description: IT 개발에 관한 글과 생활하면서 느끼는 이런저런 내용들을 정리하는 블로그

url: "https://thesoul214.github.io"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/7078805?s=460&v=4

github_profile: "https://github.com/thesoul214"
user: "bongsu Kim" # Appears at sidebar
user_email: "thesoul214@gmail.com" # Appears at sidebar, remove whole variable if unwanted
linkedin: "https://www.linkedin.com/in/kim-bongsu-0a440430"
contact_url: "https://goo.gl/forms/14Qrhb1hZx2Tdzhv1"

# google_tracking_id: "UA-120953628-2"
google_tracking_id: 

disqus_shortname: "https-thesoul214-github-io"
comments: 3

paginate: 5

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
